### ISSUE TITLE
What is the status of this project?

### ISSUE THREAD

**Issue by heme** [leonidas/transparency#125]
@pyykkis ,

Can we get an official statement on the status of this project? There has not been any activity for sometime.  I realize that available time and interests change; I am just looking to understand what the future holds for this project.

A few specific questions...
1. Do the maintainers just not have time for this project?
2. Do they not see project this as a useful tool anymore?
3. Is there a popular fork that is taking over new features/bug fixes?

There is also a similar question Google Groups here:
https://groups.google.com/forum/#!topic/transparencyjs/qIjEfdHkQ4w

This is not meant to be a demanding message. I thank all the maintainers for a great project!

**Comment by pyykkis** [comment]
Hi all,

The project is coming alive again. @rikukissa volunteered to be another maintainer, and we are looking for others. Anyone with accepted pull request will get commit access.

There's one urgent issue, #130, otherwise I believe development will just focus on occasional bug fixes. 

I have some plans for larger composition of GUI libraries, borrowing some ideas from React.js, but looking for more simple API and internal implementation. However, I'm currently focusing on completely different domain, and not planning to do any significant MV* library development in the next 12 months or so.

**Comment by pyykkis** [comment]
Also, the project is looking for new maintainers: https://github.com/leonidas/transparency/blob/master/README.md#community

Let me know, if anyone is interested. Existing fork and further development is a bonus.

**Comment by dlibanori** [comment]
@pyykkis I would love to be a maintainer, but I would end up rewriting it in a functional approach. :cry:
