### ISSUE TITLE
Is project alive?

### ISSUE THREAD

**Issue by me-ascii** [leonidas/transparency#126]

**Comment by pyykkis** [comment]
Hi,

The project is coming alive again. @rikukissa volunteered to be another maintainer, and we are looking for others. Anyone with accepted pull request will get commit access.

There's one urgent issue, #130, otherwise I believe development will just focus on occasional bug fixes. 

I have some plans for larger composition of GUI libraries, borrowing some ideas from React.js, but looking for more simple API and internal implementation. However, I'm currently focusing on completely different domain, and not planning to do any significant MV* library development in the next 12 months or so.

**Comment by pyykkis** [comment]
Also, the project is looking for new maintainers: https://github.com/leonidas/transparency/blob/master/README.md#community
